version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --port 6379 --requirepass redis

  haste:
    container_name: hasteserver
    image: ghcr.io/skyra-project/haste-server:latest
    build: .
    restart: 'no'
    depends_on:
      - redis
    ports:
      - '8290:8290'
    environment:
      PORT: 8290
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      REDIS_DB: 2
      REDIS_EXPIRE_SECONDS: 21600
